### ISSUE TITLE
Nuevos objetivos antes de un nuevo lanzamiento (Agosto 2021)

### ISSUE THREAD

**Issue by DiddiLeija** [ControlDeAgua/ControlDeAgua#9]
Tenemos algunos pendientes que resolver antes de presentar alguna versión nueva:

- [x] Reestructurar la lógica del odómetro (#8)
- [x] Añadir la opción de no registrar ingreso (Introducido accidentalmente por #11, para ser implementado por #10)
- [x] Modificar el reporte de ventas (#12)

**Comment by DiddiLeija** [comment]
Todo listo, por ahora. Hablaré con el cliente, a ver qué dice de estos cambios. Por ahora, crearé una versión nueva.
